apiversion: app/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
    spec:
      containers:
        - name: backend
          image: vikke82/lemp-backend:1.0.2
          ports:
            - containerPort:8000
          env:
            - name: DB_HOST
              valueForm:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_USER
              valueForm:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DN_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueForm:
              secretkeyRef:
                name: mysql-secret
                key: DB_PASSWORD